//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odec.CP.Server.Model.MembershipBased.Menu.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201605021129573_MenuRoleInitial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201605021129573_MenuRoleInitial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("odec.CP.Server.Model.MembershipBased.Menu.Migrations.201605021129573_MenuRoleInit" +
                            "ial", typeof(_201605021129573_MenuRoleInitial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0dXW/ktvG9QP+DsE9JcfHal7ZID+sEF/ucGr0veO+CvhmylvYJ0cdG0l5sFP1lfehP6l8oKVESP4YUKVFa7WVxwMErkkPOcGZIDocz//vPf1c/PMaR9xlleZgm54uzk9OFh5Ig3YTJw/liV9x/893ih+//+IfVq0386P1c1/uW1MMtk/x88akoti+Wyzz4hGI/P4nDIEvz9L44CdJ46W/S5fPT078tz86WCINYYFiet7rZJUUYo/IH/nmRJgHaFjs/epNuUJTT77hkXUL13voxyrd+gM4XuEJwskYZHvNJWfvkDYrv8MA+hds3KNmdYGAFeiwW3sso9PH41ii6X3h+kqSFX+DRv/iYo3WRpcnDeos/+NGHpy3C9e79KEcUqxdtdVMET58TBJdtwxpUsMuLNLYEePYtpdhSbN6L7ouGopimrzDtiyeCdUnX8wUh23WB4hsUlV38lKW77cITe35xEWWkFTwHmPIgnGceXPtZw02nJ+Tf [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
