//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odec.Menu.Service.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlossaryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal GlossaryResource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("odec.Menu.Service.Resources.GlossaryResource", typeof(GlossaryResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Code.
        /// </summary>
        public static string CodeDisplay {
            get {
                return ResourceManager.GetString("CodeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Created.
        /// </summary>
        public static string DateCreatedDisplay {
            get {
                return ResourceManager.GetString("DateCreatedDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Updated.
        /// </summary>
        public static string DateUpdatedDisplay {
            get {
                return ResourceManager.GetString("DateUpdatedDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to IsActive.
        /// </summary>
        public static string IsActiveDisplay {
            get {
                return ResourceManager.GetString("IsActiveDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name.
        /// </summary>
        public static string NameDisplay {
            get {
                return ResourceManager.GetString("NameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Short Name.
        /// </summary>
        public static string ShortNameDisplay {
            get {
                return ResourceManager.GetString("ShortNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sort Order.
        /// </summary>
        public static string SortOrderDisplay {
            get {
                return ResourceManager.GetString("SortOrderDisplay", resourceCulture);
            }
        }
    }
}
